version: '2'
services:
  db:
    image: "postgres:13.3"
    restart: always
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - /root/data/go-server/db_13_3:/var/lib/postgresql/data
    shm_size: '2gb'
    logging:
      driver: journald

  web:
    build: .
    depends_on:
      - db
    links:
      - db
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    env_file:
      - .env
    logging:
      driver: journald

  backup:
    build: .
    command: bin/backup
    restart: always
    volumes:
      - /root/data/library/backups:/backups
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
    logging:
      driver: journald
