package tag
import "fmt"
func A(c ...fmt.Stringer) Element { return Tag("a", c...) }
func Abbr(c ...fmt.Stringer) Element { return Tag("abbr", c...) }
func Acronym(c ...fmt.Stringer) Element { return Tag("acronym", c...) }
func Address(c ...fmt.Stringer) Element { return Tag("address", c...) }
func Applet(c ...fmt.Stringer) Element { return Tag("applet", c...) }
func B(c ...fmt.Stringer) Element { return Tag("b", c...) }
func Basefont(c ...fmt.Stringer) Element { return Tag("basefont", c...) }
func Bdo(c ...fmt.Stringer) Element { return Tag("bdo", c...) }
func Big(c ...fmt.Stringer) Element { return Tag("big", c...) }
func Blockquote(c ...fmt.Stringer) Element { return Tag("blockquote", c...) }
func Body(c ...fmt.Stringer) Element { return Tag("body", c...) }
func Button(c ...fmt.Stringer) Element { return Tag("button", c...) }
func Caption(c ...fmt.Stringer) Element { return Tag("caption", c...) }
func Center(c ...fmt.Stringer) Element { return Tag("center", c...) }
func Cite(c ...fmt.Stringer) Element { return Tag("cite", c...) }
func Code(c ...fmt.Stringer) Element { return Tag("code", c...) }
func Colgroup(c ...fmt.Stringer) Element { return Tag("colgroup", c...) }
func Dd(c ...fmt.Stringer) Element { return Tag("dd", c...) }
func Del(c ...fmt.Stringer) Element { return Tag("del", c...) }
func Dfn(c ...fmt.Stringer) Element { return Tag("dfn", c...) }
func Dir(c ...fmt.Stringer) Element { return Tag("dir", c...) }
func Div(c ...fmt.Stringer) Element { return Tag("div", c...) }
func Dl(c ...fmt.Stringer) Element { return Tag("dl", c...) }
func Dt(c ...fmt.Stringer) Element { return Tag("dt", c...) }
func Em(c ...fmt.Stringer) Element { return Tag("em", c...) }
func Fieldset(c ...fmt.Stringer) Element { return Tag("fieldset", c...) }
func Font(c ...fmt.Stringer) Element { return Tag("font", c...) }
func Form(c ...fmt.Stringer) Element { return Tag("form", c...) }
func H1(c ...fmt.Stringer) Element { return Tag("h1", c...) }
func H2(c ...fmt.Stringer) Element { return Tag("h2", c...) }
func H3(c ...fmt.Stringer) Element { return Tag("h3", c...) }
func H4(c ...fmt.Stringer) Element { return Tag("h4", c...) }
func H5(c ...fmt.Stringer) Element { return Tag("h5", c...) }
func H6(c ...fmt.Stringer) Element { return Tag("h6", c...) }
func Head(c ...fmt.Stringer) Element { return Tag("head", c...) }
func Html(c ...fmt.Stringer) Element { return Tag("html", c...) }
func I(c ...fmt.Stringer) Element { return Tag("i", c...) }
func Iframe(c ...fmt.Stringer) Element { return Tag("iframe", c...) }
func Ins(c ...fmt.Stringer) Element { return Tag("ins", c...) }
func Isindex(c ...fmt.Stringer) Element { return Tag("isindex", c...) }
func Kbd(c ...fmt.Stringer) Element { return Tag("kbd", c...) }
func Label(c ...fmt.Stringer) Element { return Tag("label", c...) }
func Legend(c ...fmt.Stringer) Element { return Tag("legend", c...) }
func Li(c ...fmt.Stringer) Element { return Tag("li", c...) }
func Map(c ...fmt.Stringer) Element { return Tag("map", c...) }
func Menu(c ...fmt.Stringer) Element { return Tag("menu", c...) }
func Noframes(c ...fmt.Stringer) Element { return Tag("noframes", c...) }
func Noscript(c ...fmt.Stringer) Element { return Tag("noscript", c...) }
func Object(c ...fmt.Stringer) Element { return Tag("object", c...) }
func Ol(c ...fmt.Stringer) Element { return Tag("ol", c...) }
func Optgroup(c ...fmt.Stringer) Element { return Tag("optgroup", c...) }
func Option(c ...fmt.Stringer) Element { return Tag("option", c...) }
func P(c ...fmt.Stringer) Element { return Tag("p", c...) }
func Pre(c ...fmt.Stringer) Element { return Tag("pre", c...) }
func Q(c ...fmt.Stringer) Element { return Tag("q", c...) }
func S(c ...fmt.Stringer) Element { return Tag("s", c...) }
func Samp(c ...fmt.Stringer) Element { return Tag("samp", c...) }
func Script(c ...fmt.Stringer) Element { return Tag("script", c...) }
func Select(c ...fmt.Stringer) Element { return Tag("select", c...) }
func Small(c ...fmt.Stringer) Element { return Tag("small", c...) }
func Span(c ...fmt.Stringer) Element { return Tag("span", c...) }
func Strike(c ...fmt.Stringer) Element { return Tag("strike", c...) }
func Strong(c ...fmt.Stringer) Element { return Tag("strong", c...) }
func Style(c ...fmt.Stringer) Element { return Tag("style", c...) }
func Sub(c ...fmt.Stringer) Element { return Tag("sub", c...) }
func Sup(c ...fmt.Stringer) Element { return Tag("sup", c...) }
func Table(c ...fmt.Stringer) Element { return Tag("table", c...) }
func Tbody(c ...fmt.Stringer) Element { return Tag("tbody", c...) }
func Td(c ...fmt.Stringer) Element { return Tag("td", c...) }
func Textarea(c ...fmt.Stringer) Element { return Tag("textarea", c...) }
func Tfoot(c ...fmt.Stringer) Element { return Tag("tfoot", c...) }
func Th(c ...fmt.Stringer) Element { return Tag("th", c...) }
func Thead(c ...fmt.Stringer) Element { return Tag("thead", c...) }
func Title(c ...fmt.Stringer) Element { return Tag("title", c...) }
func Tr(c ...fmt.Stringer) Element { return Tag("tr", c...) }
func Tt(c ...fmt.Stringer) Element { return Tag("tt", c...) }
func U(c ...fmt.Stringer) Element { return Tag("u", c...) }
func Ul(c ...fmt.Stringer) Element { return Tag("ul", c...) }
func Var(c ...fmt.Stringer) Element { return Tag("var", c...) }
func Section(c ...fmt.Stringer) Element { return Tag("section", c...) }