package attr

func Abbr(v string) Attribute { return Attr("abbr", v) }
func Accept(v string) Attribute { return Attr("accept", v) }
func AcceptCharset(v string) Attribute { return Attr("accept-charset", v) }
func Accesskey(v string) Attribute { return Attr("accesskey", v) }
func Action(v string) Attribute { return Attr("action", v) }
func Align(v string) Attribute { return Attr("align", v) }
func Alink(v string) Attribute { return Attr("alink", v) }
func Alt(v string) Attribute { return Attr("alt", v) }
func Archive(v string) Attribute { return Attr("archive", v) }
func Axis(v string) Attribute { return Attr("axis", v) }
func Background(v string) Attribute { return Attr("background", v) }
func Bgcolor(v string) Attribute { return Attr("bgcolor", v) }
func Border(v string) Attribute { return Attr("border", v) }
func Cellpadding(v string) Attribute { return Attr("cellpadding", v) }
func Cellspacing(v string) Attribute { return Attr("cellspacing", v) }
func Charset(v string) Attribute { return Attr("charset", v) }
func Checked(v string) Attribute { return Attr("checked", v) }
func Cite(v string) Attribute { return Attr("cite", v) }
func Class(v string) Attribute { return Attr("class", v) }
func Classid(v string) Attribute { return Attr("classid", v) }
func Clear(v string) Attribute { return Attr("clear", v) }
func Code(v string) Attribute { return Attr("code", v) }
func Codebase(v string) Attribute { return Attr("codebase", v) }
func Codetype(v string) Attribute { return Attr("codetype", v) }
func Color(v string) Attribute { return Attr("color", v) }
func Cols(v string) Attribute { return Attr("cols", v) }
func Colspan(v string) Attribute { return Attr("colspan", v) }
func Compact(v string) Attribute { return Attr("compact", v) }
func Content(v string) Attribute { return Attr("content", v) }
func Coords(v string) Attribute { return Attr("coords", v) }
func Data(v string) Attribute { return Attr("data", v) }
func Datetime(v string) Attribute { return Attr("datetime", v) }
func Declare(v string) Attribute { return Attr("declare", v) }
func Defer(v string) Attribute { return Attr("defer", v) }
func Dir(v string) Attribute { return Attr("dir", v) }
func Disabled(v string) Attribute { return Attr("disabled", v) }
func Enctype(v string) Attribute { return Attr("enctype", v) }
func Face(v string) Attribute { return Attr("face", v) }
func For(v string) Attribute { return Attr("for", v) }
func Frame(v string) Attribute { return Attr("frame", v) }
func Frameborder(v string) Attribute { return Attr("frameborder", v) }
func Headers(v string) Attribute { return Attr("headers", v) }
func Height(v string) Attribute { return Attr("height", v) }
func Href(v string) Attribute { return Attr("href", v) }
func Hreflang(v string) Attribute { return Attr("hreflang", v) }
func Hspace(v string) Attribute { return Attr("hspace", v) }
func HttpEquiv(v string) Attribute { return Attr("http-equiv", v) }
func Id(v string) Attribute { return Attr("id", v) }
func Ismap(v string) Attribute { return Attr("ismap", v) }
func Label(v string) Attribute { return Attr("label", v) }
func Lang(v string) Attribute { return Attr("lang", v) }
func Language(v string) Attribute { return Attr("language", v) }
func Link(v string) Attribute { return Attr("link", v) }
func Longdesc(v string) Attribute { return Attr("longdesc", v) }
func Marginheight(v string) Attribute { return Attr("marginheight", v) }
func Marginwidth(v string) Attribute { return Attr("marginwidth", v) }
func Maxlength(v string) Attribute { return Attr("maxlength", v) }
func Media(v string) Attribute { return Attr("media", v) }
func Method(v string) Attribute { return Attr("method", v) }
func Multiple(v string) Attribute { return Attr("multiple", v) }
func Name(v string) Attribute { return Attr("name", v) }
func Nohref(v string) Attribute { return Attr("nohref", v) }
func Noshade(v string) Attribute { return Attr("noshade", v) }
func Nowrap(v string) Attribute { return Attr("nowrap", v) }
func Object(v string) Attribute { return Attr("object", v) }
func Onblur(v string) Attribute { return Attr("onblur", v) }
func Onchange(v string) Attribute { return Attr("onchange", v) }
func Onfocus(v string) Attribute { return Attr("onfocus", v) }
func Onload(v string) Attribute { return Attr("onload", v) }
func Onreset(v string) Attribute { return Attr("onreset", v) }
func Onselect(v string) Attribute { return Attr("onselect", v) }
func Onsubmit(v string) Attribute { return Attr("onsubmit", v) }
func Onunload(v string) Attribute { return Attr("onunload", v) }
func Profile(v string) Attribute { return Attr("profile", v) }
func Prompt(v string) Attribute { return Attr("prompt", v) }
func Readonly(v string) Attribute { return Attr("readonly", v) }
func Rel(v string) Attribute { return Attr("rel", v) }
func Rev(v string) Attribute { return Attr("rev", v) }
func Rows(v string) Attribute { return Attr("rows", v) }
func Rowspan(v string) Attribute { return Attr("rowspan", v) }
func Rules(v string) Attribute { return Attr("rules", v) }
func Scheme(v string) Attribute { return Attr("scheme", v) }
func Scope(v string) Attribute { return Attr("scope", v) }
func Scrolling(v string) Attribute { return Attr("scrolling", v) }
func Selected(v string) Attribute { return Attr("selected", v) }
func Shape(v string) Attribute { return Attr("shape", v) }
func Size(v string) Attribute { return Attr("size", v) }
func Span(v string) Attribute { return Attr("span", v) }
func Src(v string) Attribute { return Attr("src", v) }
func Standby(v string) Attribute { return Attr("standby", v) }
func Start(v string) Attribute { return Attr("start", v) }
func Style(v string) Attribute { return Attr("style", v) }
func Summary(v string) Attribute { return Attr("summary", v) }
func Tabindex(v string) Attribute { return Attr("tabindex", v) }
func Target(v string) Attribute { return Attr("target", v) }
func Text(v string) Attribute { return Attr("text", v) }
func Title(v string) Attribute { return Attr("title", v) }
func Type(v string) Attribute { return Attr("type", v) }
func Usemap(v string) Attribute { return Attr("usemap", v) }
func Value(v string) Attribute { return Attr("value", v) }
func Valuetype(v string) Attribute { return Attr("valuetype", v) }
func Vlink(v string) Attribute { return Attr("vlink", v) }
func Vspace(v string) Attribute { return Attr("vspace", v) }
func Width(v string) Attribute { return Attr("width", v) }
func XmlLang(v string) Attribute { return Attr("xml:lang", v) }
func XmlSpace(v string) Attribute { return Attr("xml:space", v) }
func Xmlns(v string) Attribute { return Attr("xmlns", v) }